"""
Django settings for infinity_meme project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import sys

from celery import Celery
from envparse import env

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'rabz*%q!m*zrf_v4&y6eglcx1e+7^ns50=#=2m^kp34=bm%jgy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

# Celery
REDIS_HOST = env.str('REDIS_HOST')
REDIS_PORT = env.int('REDIS_PORT')
REDIS_DB = env.int('REDIS_DB')

app = Celery('infinity-meme')
app.config_from_object('django.conf:settings')
app.conf.broker_url = f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}'

# Telegram
TELEGRAM_API_KEY = env.str('TELEGRAM_API_KEY')


# Application definition

INSTALLED_APPS = [
    'django.contrib.contenttypes',

    # External.
    'django_extensions',
    'polymorphic',

    # Internal
    'storage.apps.StorageConfig',
    'image.apps.ImageConfig',
    'parsers.apps.ParsersConfig',
    'post.apps.PostConfig',
]

WSGI_APPLICATION = 'infinity_meme.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': env.str('DB_NAME'),
        'HOST': env.str('DB_HOST'),
        'USER': env.str('DB_USER'),
        'PASSWORD': env.str('DB_PASSWORD'),
        'PORT': env.int('DB_PORT'),
    }
}

USE_TZ = True
