# Generated by Django 3.2 on 2021-04-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tg_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('user_id', models.PositiveIntegerField()),
                ('post_tg_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('posted_at', models.DateTimeField(null=True)),
                ('reviewed_rating', models.PositiveIntegerField(default=0)),
                ('on_review', models.BooleanField(default=False)),
                ('images', models.ManyToManyField(to='image.Image')),
                ('posted_to', models.ManyToManyField(to='post.Channel')),
                ('reviewed_by', models.ManyToManyField(to='post.Reviewer')),
            ],
        ),
    ]
