# Generated by Django 3.2 on 2021-04-29 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('name', models.UUIDField()),
                ('ext', models.CharField(max_length=10)),
                ('size', models.PositiveIntegerField()),
                ('src', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now=True)),
                ('src_url', models.CharField(max_length=100)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='storage.storage')),
            ],
        ),
    ]
